// <auto-generated />
using System;
using Gym.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623214856_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Gym.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1995, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Пётр",
                            LastName = "Иванов",
                            Phone = "+7 (900) 111-11-11",
                            RegistrationDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1998, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Анна",
                            LastName = "Петрова",
                            Phone = "+7 (900) 222-22-22",
                            RegistrationDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1990, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Олег",
                            LastName = "Сидоров",
                            Phone = "+7 (900) 333-33-33",
                            RegistrationDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2000, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Мария",
                            LastName = "Козлова",
                            Phone = "+7 (900) 444-44-44",
                            RegistrationDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1988, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Дмитрий",
                            LastName = "Новиков",
                            Phone = "+7 (900) 555-55-55",
                            RegistrationDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Gym.Data.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 2500m,
                            StartDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Активен",
                            Type = "30 дней"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            EndDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 6500m,
                            StartDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Активен",
                            Type = "90 дней"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            EndDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 2500m,
                            StartDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Истёк",
                            Type = "30 дней"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            EndDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 2500m,
                            StartDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Активен",
                            Type = "30 дней"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 5,
                            EndDate = new DateTime(2027, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 22000m,
                            StartDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Активен",
                            Type = "365 дней"
                        });
                });

            modelBuilder.Entity("Gym.Data.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityType = "Тренажёрный зал",
                            ClientId = 1,
                            DateTime = new DateTime(2026, 6, 22, 10, 0, 0, 0, DateTimeKind.Local),
                            SubscriptionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivityType = "Бассейн",
                            ClientId = 2,
                            DateTime = new DateTime(2026, 6, 23, 18, 0, 0, 0, DateTimeKind.Local),
                            SubscriptionId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActivityType = "Тренажёрный зал",
                            ClientId = 1,
                            DateTime = new DateTime(2026, 6, 24, 9, 0, 0, 0, DateTimeKind.Local),
                            SubscriptionId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActivityType = "Групповое занятие",
                            ClientId = 4,
                            DateTime = new DateTime(2026, 6, 21, 12, 0, 0, 0, DateTimeKind.Local),
                            SubscriptionId = 4
                        },
                        new
                        {
                            Id = 5,
                            ActivityType = "Йога",
                            ClientId = 5,
                            DateTime = new DateTime(2026, 6, 19, 8, 0, 0, 0, DateTimeKind.Local),
                            SubscriptionId = 5
                        });
                });

            modelBuilder.Entity("Gym.Data.Models.Subscription", b =>
                {
                    b.HasOne("Gym.Data.Models.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Gym.Data.Models.Visit", b =>
                {
                    b.HasOne("Gym.Data.Models.Client", "Client")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gym.Data.Models.Subscription", "Subscription")
                        .WithMany("Visits")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Gym.Data.Models.Client", b =>
                {
                    b.Navigation("Subscriptions");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Gym.Data.Models.Subscription", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
